# pragma once

# define _BRIGHT_RED		"\033[91m"
# define _BRIGHT_GREEN		"\033[92m"
# define _BRIGHT_YELLOW		"\033[93m"
# define _BRIGHT_BLUE		"\033[94m"
# define _BRIGHT_MAGENTA	"\033[95m"
# define _BRIGHT_CYAN		"\033[96m"
# define _BRIGHT_WHITE		"\033[97m"
# define _GRAY				"\033[90m"
# define _BG_RED			"\033[41m"
# define _BG_GREEN			"\033[42m"
# define _BG_YELLOW			"\033[43m"
# define _BG_BLUE			"\033[44m"
# define _BG_MAGENTA		"\033[45m"
# define _BG_CYAN			"\033[46m"
# define _BG_WHITE			"\033[47m"
# define _RED				"\033[1;31m"
# define _GREEN				"\033[1;32m"
# define _YELLOW			"\033[1;33m"
# define _BLUE				"\033[1;34m"
# define _BOLD				"\033[1m"
# define _CYAN				"\033[1;36m"
# define _MAGENTA			"\033[1;35m"
# define _WHITE				"\033[1;37m"
# define _BLACK				"\033[1;30m"
# define _UNDERLINE			"\033[4m"
# define _REVERSED			"\033[7m"
# define _RESET				"\033[0m"

# define BRIGHT_RED			std::string(_BRIGHT_RED)
# define BRIGHT_GREEN		std::string(_BRIGHT_GREEN)
# define BRIGHT_YELLOW		std::string(_BRIGHT_YELLOW)
# define BRIGHT_BLUE		std::string(_BRIGHT_BLUE)
# define BRIGHT_MAGENTA		std::string(_BRIGHT_MAGENTA)
# define BRIGHT_CYAN		std::string(_BRIGHT_CYAN)
# define BRIGHT_WHITE		std::string(_BRIGHT_WHITE)
# define GRAY				std::string(_GRAY)
# define BG_RED				std::string(_BG_RED)
# define BG_GREEN			std::string(_BG_GREEN)
# define BG_YELLOW			std::string(_BG_YELLOW)
# define BG_BLUE			std::string(_BG_BLUE)
# define BG_MAGENTA			std::string(_BG_MAGENTA)
# define BG_CYAN			std::string(_BG_CYAN)
# define BG_WHITE			std::string(_BG_WHITE)
# define RED				std::string(_RED)
# define GREEN				std::string(_GREEN)
# define YELLOW				std::string(_YELLOW)
# define BLUE				std::string(_BLUE)
# define BOLD				std::string(_BOLD)
# define CYAN				std::string(_CYAN)
# define MAGENTA			std::string(_MAGENTA)
# define WHITE				std::string(_WHITE)
# define BLACK				std::string(_BLACK)
# define UNDERLINE			std::string(_UNDERLINE)
# define REVERSED			std::string(_REVERSED)
# define RESET				std::string(_RESET)
